---
- name: stop mysql
  service:
    name: mysql
    state: stopped
- name: start mysql
  service:
    name: mysql
    state: statred
- name: restart mysql
  service:
    name: mysql
    state: restarted
- name:  modify the first node mysql.cnf 
  template:
    srv: mysqld-first.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
